- hosts: servers

  tasks:
    - name: ensure docker network exists
      docker_network:
        name: decluster_network

    - name: run portainer
      docker_container:
        name: portainer
        image: portainer/portainer
        ports:
          - "8888:8000"
          - "9999:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /data/portainer:/data