- hosts: servers

  tasks:
    - name: get spark batch app from git
      git:
        repo: git@github.com:bigdata1819group5/batch_process.git
        dest: "{{ setup_stage }}/batch_process"

    - name: build spark batch process app image
      docker_image:
        name: spark-batch
        build:
          path: "{{ setup_stage }}/batch_process"
          pull: no
        source: build
        force_source: yes

    - name: ensure docker network exists
      docker_network:
        name: decluster_network

    - name: run spark master instances
      docker_container:
        name: spark-batch
        image: spark-batch
        env:
          SPARK_MASTER_NAME: spark-master
          SPARK_MASTER_PORT: "7077"
          ENABLE_INIT_DAEMON: "false"
          BATCH_CASSANDRA_DISTANCE_TABLE: vehicles_covered_distance
          BATCH_CASSANDRA_KEYSPACE: streaming
          BATCH_APP_NAME: BatchProcessData
          BATCH_CASSANDRA_HOST: cassandra-1
          BATCH_HADOOP_NAMENODE: hdfs://namenode:8020
        networks_cli_compatible: yes
        networks:
          - name: decluster_network
            aliases:
              - spark-batch