- hosts: servers

  tasks:
    - name: get spark digest app from git
      git:
        repo: git@github.com:bigdata1819group5/data_digest.git
        dest: "{{ setup_stage }}/spark_digest"

    - name: build spark digest app image
      docker_image:
        name: spark-digest
        build:
          path: "{{ setup_stage }}/spark_digest"
          pull: no
        source: build
        force_source: yes

    - name: ensure docker network exists
      docker_network:
        name: decluster_network

    - name: run spark master instances
      docker_container:
        name: spark-digest
        image: spark-digest
        env:
          SPARK_MASTER_NAME: spark-master
          SPARK_MASTER_PORT: "7077"
          ENABLE_INIT_DAEMON: "false"
          DIGEST_CASSANDRA_TILE_TABLE: vehicles_by_tileid
          DIGEST_CASSANDRA_VEHICLE_TABLE: vehicles_by_company
          DIGEST_CASSANDRA_KEYSPACE: streaming
          DIGEST_CASSANDRA_HOST: cassandra-1
          DIGEST_KAFKA_SERVERS: kafka-1:19092,kafka-2:29092,kafka-3:39092
          DIGEST_CONSUMER_GROUP_ID: DigestGroup
          DIGEST_TOPICS: vehiclelocation
          DIGEST_HADOOP_NAMENODE: hdfs://namenode:8020
          DIGEST_CORES_MAX: "8"
        networks_cli_compatible: yes
        networks:
          - name: decluster_network
            aliases:
              - spark-digest